### ISSUE TITLE
Notifications icon has red status icon

### ISSUE THREAD

**Issue by marcinjahn** [Ordissimo/Big-Sur-StatusArea#48]
I'm seeing this:
![image](https://user-images.githubusercontent.com/10273406/140494096-b5056d9d-3171-4d66-b453-355612d2abef.png)

I have no notifications at the moment. Shouldn't the red circle disappear?

**Comment by Ordissimo** [comment]
You don't give enough detail about your system!
Which version of gnome-shell are you using?
What version of the extension do you have?

**Comment by marcinjahn** [comment]
Sorry, here it is:
Fedora 35 
Gnome 41.1
Extension V27

Screenshot with notifications open:
![image](https://user-images.githubusercontent.com/10273406/140523755-56933c25-550e-4317-9de8-4e93bba7b10a.png)

**Comment by Ordissimo** [comment]
I look in the weekend, I do not have your version!
indeed the red circle should not be visible!

**Comment by marcinjahn** [comment]
I installed it from the Gnome Extensions website.

**Comment by Ordissimo** [comment]
I can imagine.
I use the icons of your theme. and usually this problem is there when the theme does not provide all the icons...

**Comment by kcken** [comment]
This started with the new version of Gnome and Fedora 35.  This worked fine in Fedora 34 (with the same theme applied).  Something changed in how the shell is picking icons because my volume icon disappeared as well.

**Comment by marcinjahn** [comment]
@kcken My volume icon is fine: 
![image](https://user-images.githubusercontent.com/10273406/140550963-90b1a7a6-d978-45d5-aaa6-4b77c1773239.png)

**Comment by kcken** [comment]
Turned out my volume icon was due to a Fedora update that broke audio (problem with upgrading from 34 to 35 and the audio subsystem change) - fixed that now, and the volume icon is back.  With regards to the problem with notifications - I fixed it in notifications.js - I changed: 

 const NoNotifications = 'task-past-due-symbolic';
 const NewNotifications = 'task-due-symbolic';

to

 const NoNotifications = 'task-none-symbolic'; 
 const NewNotifications = 'task-due-symbolic';

I then created a task-none-symbolic icon (attached) and placed it in the same directory as task-due-symbolic which on my system was ~/.icons/BigSur/status/symbolic

With this change, when there are no notifications, the clipboard is blank.

Another option would be to use the 2 existing notification icons "notification-symbolic" and "notification-new-symbolic" as those already exist, and properly show the state of existing notifications (on my system those are a bell icon as opposed to a clipboard icon)

const NoNotifications = 'notification-symbolic'; 
 const NewNotifications = 'notification-new-symbolic';

Anyway, hope this helps!

[task-none-symbolic.zip](https://github.com/Ordissimo/Big-Sur-StatusArea/files/7513067/task-none-symbolic.zip)

**Comment by Ordissimo** [comment]
Hi @kcken,
Thanks for the feedback, I will make a mix of all of these!
The icons are theme dependent, I took the option to remove the extension icons to use the system one provided by the theme.
We all have a different distribution or theme.
Your feedback brings me a lot, are you able to propose a pull-request ?

**Comment by luca-martino** [comment]
On my environment the "notification-symbolic" and "notification-new-symbolic" are more consistent.

`const NoNotifications = 'notification-symbolic';`
`const NewNotifications = 'notification-new-symbolic';`

**Comment by Ordissimo** [comment]
Hi All,
Some functions are not working since the migration to the new gnome-shell formalism.
This generates a lot of feedback from you (all),
I'm solving this problem as a priority ! 
I'll work on your problem in the next days, but I can't change the icons as you suggest, the solution must be global and not only turned to your distribution.

**Comment by luca-martino** [comment]
> > On my environment the "notification-symbolic" and "notification-new-symbolic" are more consistent.
> > `const NoNotifications = 'notification-symbolic';` `const NewNotifications = 'notification-new-symbolic';`
> 
> What is your environment? Can you be more specific. OS:? gnome-shell:? Wayland | X11:? Default theme? Default icons?

OS: Fedora release 35
DE: GNOME 41.4
Theme: WhiteSur-dark
Icons: WhiteSur-dark
... but with latest release of Big-Sur-StatusArea [3c1e253](https://github.com/Ordissimo/Big-Sur-StatusArea/commit/3c1e253d1ae729d37dfbbd5f472362d35d1d1567) it's ok

**Comment by Ordissimo** [comment]
Thanks for the feedback and thanks for the contribution of @AI-ien!
